const ALL_SPOTS = [
  { id: 1, campName: '松岭森林营地', spotName: 'A区1号营位', area: 'A区', location: '黑龙江省伊春市乌伊岭区', latitude: 48.22, longitude: 129.45, priceNum: 900, priceUnit: '/天', price: '¥900/天', rating: '4.8', imgs: ['/images/camp-forest.png', '/images/camp-lake.png'], terrainType: '森林', facilities: ['无线网', '水电', '淋浴', '烧烤区'], desc: '在森林中体验露营乐趣。营位配有水电、淋浴设施，适合家庭出游。', contentBlocks: [{ type: 'text', content: '在森林中体验露营乐趣。营位配有水电、淋浴设施，适合家庭出游。周边环境清幽，空气清新，适合周末放松。' }, { type: 'image', src: '/images/camp-forest.png' }, { type: 'text', content: 'A区营位紧邻林道，停车便捷，适合自驾露营。配备独立插座与水源，支持过夜露营。' }] },
  { id: 2, campName: '松岭森林营地', spotName: 'A区2号营位', area: 'A区', location: '黑龙江省伊春市乌伊岭区', priceNum: 850, priceUnit: '/天', price: '¥850/天', rating: '4.7', imgs: ['/images/camp-forest.png'], terrainType: '森林', facilities: ['水电', '淋浴'] },
  { id: 3, campName: '水晶湖豪华露营', spotName: '湖畔观景营位', area: '湖畔', location: '四川省阿坝州九寨沟县', latitude: 33.22, longitude: 103.92, priceNum: 1800, priceUnit: '/天', price: '¥1800/天', rating: '4.9', imgs: ['/images/camp-lake.png', '/images/camp-forest.png'], terrainType: '湖畔', facilities: ['无线网', '厨房', '热水浴缸', '皮划艇租赁'], desc: '在湖边体验豪华露营。我们的豪华帐篷配有大号床、私人甲板，可欣赏清澈湖水的壮丽景色。', contentBlocks: [{ type: 'text', content: '在湖边体验豪华露营。我们的豪华帐篷配有大号床、私人甲板，可欣赏清澈湖水的壮丽景色。' }, { type: 'image', src: '/images/camp-lake.png' }, { type: 'text', content: '室内配备空调与独立卫浴，甲板上可进行户外用餐。皮划艇租赁点步行 2 分钟可达。' }] },
  { id: 4, campName: '阿尔卑斯山基地', spotName: '雪山观景营位', area: '雪山', location: '云南省迪庆州德钦县', priceNum: 1200, priceUnit: '/天', price: '¥1200/天', rating: '4.7', imgs: ['/images/camp-alps.png', '/images/camp-forest.png'], terrainType: '山地', facilities: ['水电', '观景台'] },
  { id: 5, campName: '日落海滩度假村', spotName: '沙滩A区营位', area: '沙滩A区', location: '海南省三亚市海棠区', priceNum: 950, priceUnit: '/天', price: '¥950/天', rating: '4.6', imgs: ['/images/camp-beach.png', '/images/camp-lake.png'], terrainType: '海滩', facilities: ['水电', '淋浴', '烧烤区'] },
  { id: 6, campName: '极简现代小屋', spotName: '独栋01号营位', area: '独栋', location: '浙江省杭州市余杭区', priceNum: 2200, priceUnit: '/天', price: '¥2200/天', rating: '5', imgs: ['/images/camp-modern.png', '/images/camp-forest.png'], terrainType: '森林', facilities: ['独立卫浴', '空调', 'WiFi'] },
  { id: 7, campName: '静谧湖畔营地', spotName: '湖景1号营位', area: '湖景', location: '河北省承德市围场县', priceNum: 550, priceUnit: '/天', price: '¥550/天', rating: '4.6', imgs: ['/images/camp-lake.png', '/images/camp-beach.png'], terrainType: '湖畔', facilities: ['水电', '钓鱼'] },
  { id: 8, campName: '静谧湖畔营地', spotName: '湖景2号营位', area: '湖景', location: '河北省承德市围场县', priceNum: 520, priceUnit: '/天', price: '¥520/天', rating: '4.5', imgs: ['/images/camp-lake.png'], terrainType: '湖畔', facilities: ['水电'] },
  { id: 9, campName: '云端山巅营地', spotName: '山脊观星营位', area: '山脊', location: '四川省甘孜州泸定县', priceNum: 1200, priceUnit: '/天', price: '¥1200/天', rating: '4.9', imgs: ['/images/camp-alps.png', '/images/camp-modern.png'], terrainType: '山地', facilities: ['观星', '观景台'] },
  { id: 10, campName: '松岭森林营地', spotName: 'B区3号营位', area: 'B区', location: '黑龙江省伊春市乌伊岭区', priceNum: 820, priceUnit: '/天', price: '¥820/天', rating: '4.6', imgs: ['/images/camp-forest.png'], terrainType: '森林', facilities: ['水电', '淋浴'] },
  { id: 101, campName: '松岭森林营地', spotName: 'A区1号营位', area: 'A区', location: '黑龙江省伊春市乌伊岭区', priceNum: 900, priceUnit: '/天', price: '¥900/天', rating: '4.8', imgs: ['/images/camp-forest.png', '/images/camp-lake.png'], terrainType: '森林', facilities: ['水电', '淋浴', '烧烤区'] },
  { id: 102, campName: '水晶湖豪华露营', spotName: '湖畔观景营位', area: '湖畔', location: '四川省阿坝州九寨沟县', priceNum: 1800, priceUnit: '/天', price: '¥1800/天', rating: '4.9', imgs: ['/images/camp-lake.png', '/images/camp-forest.png'], terrainType: '湖畔', facilities: ['水电', '淋浴', '烧烤区', 'WiFi'] },
  { id: 103, campName: '阿尔卑斯山基地', spotName: '雪山观景营位', area: '雪山', location: '云南省迪庆州德钦县', priceNum: 1200, priceUnit: '/天', price: '¥1200/天', rating: '4.7', imgs: ['/images/camp-alps.png', '/images/camp-forest.png'], terrainType: '山地', facilities: ['水电', '观景台'] },
  { id: 104, campName: '日落海滩度假村', spotName: '沙滩A区营位', area: '沙滩A区', location: '海南省三亚市海棠区', priceNum: 950, priceUnit: '/天', price: '¥950/天', rating: '4.6', imgs: ['/images/camp-beach.png', '/images/camp-lake.png'], terrainType: '海滩', facilities: ['水电', '淋浴', '烧烤区'] },
  { id: 105, campName: '极简现代小屋', spotName: '独栋01号营位', area: '独栋', location: '浙江省杭州市余杭区', priceNum: 2200, priceUnit: '/天', price: '¥2200/天', rating: '5', imgs: ['/images/camp-modern.png', '/images/camp-forest.png'], terrainType: '森林', facilities: ['独立卫浴', '空调', 'WiFi'] },
  { id: 106, campName: '静谧湖畔营地', spotName: '湖景1号营位', area: '湖景', location: '河北省承德市围场县', priceNum: 550, priceUnit: '/天', price: '¥550/天', rating: '4.6', imgs: ['/images/camp-lake.png', '/images/camp-beach.png'], terrainType: '湖畔', facilities: ['水电', '钓鱼'] },
  { id: 107, campName: '云端山巅营地', spotName: '山脊观星营位', area: '山脊', location: '四川省甘孜州泸定县', priceNum: 1300, priceUnit: '/天', price: '¥1300/天', rating: '4.9', imgs: ['/images/camp-alps.png', '/images/camp-modern.png'], terrainType: '山地', facilities: ['观星', '观景台'] }
]

function getById(id) {
  return ALL_SPOTS.find(s => String(s.id) === String(id)) || null
}

module.exports = { ALL_SPOTS, getById }
